### ISSUE TITLE
Wie formatiere ich mein README? - Ein paar Links und Beispiele

### ISSUE THREAD

**Issue by karlamitk** [patmu04/cubefactory#5]
Guckst du hier:https://github.com/karlamitk/testrep/blob/master/Anleitungen/Anleitung_Markdown.md

**Comment by patmu04** [comment]
der Markdown Editor, den Karla heute kurz gezeigt hat:
http://dillinger.io/
dort kann man recht praktisch nebeneinander in markdown schreiben und rechts direkt die Vorschau sehen

**Comment by jbon** [comment]
ich benutze den Editor namens "texts" http://www.texts.io/

**Comment by karlamitk** [comment]
ich hab die Anleitung für Links innerhalb des Dokuments berichtigt.
